/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ApiAppointmentsRouteImport } from './routes/api/appointments'
import { Route as ApiInquiriesRouteImport } from './routes/api/inquiries'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiVehiclesRouteImport } from './routes/api/vehicles'
import { Route as CuratorIndexRouteImport } from './routes/curator/index'
import { Route as CuratorLoginRouteImport } from './routes/curator/login'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventorySlugRouteImport } from './routes/inventory/$slug'
import { Route as ApiAppointmentsIdRouteImport } from './routes/api/appointments.$id'
import { Route as ApiInquiriesIdRouteImport } from './routes/api/inquiries.$id'
import { Route as ApiUploadsNameRouteImport } from './routes/api/uploads.$name'
import { Route as ApiVehiclesIdRouteImport } from './routes/api/vehicles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentsRoute = ApiAppointmentsRouteImport.update({
  id: '/api/appointments',
  path: '/api/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiriesRoute = ApiInquiriesRouteImport.update({
  id: '/api/inquiries',
  path: '/api/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehiclesRoute = ApiVehiclesRouteImport.update({
  id: '/api/vehicles',
  path: '/api/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorIndexRoute = CuratorIndexRouteImport.update({
  id: '/curator/',
  path: '/curator/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuratorLoginRoute = CuratorLoginRouteImport.update({
  id: '/curator/login',
  path: '/curator/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySlugRoute = InventorySlugRouteImport.update({
  id: '/inventory/$slug',
  path: '/inventory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentsIdRoute = ApiAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAppointmentsRoute,
} as any)
const ApiInquiriesIdRoute = ApiInquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInquiriesRoute,
} as any)
const ApiUploadsNameRoute = ApiUploadsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const ApiVehiclesIdRoute = ApiVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVehiclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/inquiries': typeof ApiInquiriesRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/curator/login': typeof CuratorLoginRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/curator/': typeof CuratorIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/api/appointments/$id': typeof ApiAppointmentsIdRoute
  '/api/inquiries/$id': typeof ApiInquiriesIdRoute
  '/api/uploads/$name': typeof ApiUploadsNameRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/inquiries': typeof ApiInquiriesRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/curator/login': typeof CuratorLoginRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/curator': typeof CuratorIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/api/appointments/$id': typeof ApiAppointmentsIdRoute
  '/api/inquiries/$id': typeof ApiInquiriesIdRoute
  '/api/uploads/$name': typeof ApiUploadsNameRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/inquiries': typeof ApiInquiriesRouteWithChildren
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/me': typeof ApiMeRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/curator/login': typeof CuratorLoginRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/curator/': typeof CuratorIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/api/appointments/$id': typeof ApiAppointmentsIdRoute
  '/api/inquiries/$id': typeof ApiInquiriesIdRoute
  '/api/uploads/$name': typeof ApiUploadsNameRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/api/appointments'
    | '/api/inquiries'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/stats'
    | '/api/uploads'
    | '/api/vehicles'
    | '/curator/login'
    | '/inventory/$slug'
    | '/curator/'
    | '/inventory/'
    | '/api/appointments/$id'
    | '/api/inquiries/$id'
    | '/api/uploads/$name'
    | '/api/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/api/appointments'
    | '/api/inquiries'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/stats'
    | '/api/uploads'
    | '/api/vehicles'
    | '/curator/login'
    | '/inventory/$slug'
    | '/curator'
    | '/inventory'
    | '/api/appointments/$id'
    | '/api/inquiries/$id'
    | '/api/uploads/$name'
    | '/api/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/api/appointments'
    | '/api/inquiries'
    | '/api/login'
    | '/api/logout'
    | '/api/me'
    | '/api/stats'
    | '/api/uploads'
    | '/api/vehicles'
    | '/curator/login'
    | '/inventory/$slug'
    | '/curator/'
    | '/inventory/'
    | '/api/appointments/$id'
    | '/api/inquiries/$id'
    | '/api/uploads/$name'
    | '/api/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  ApiAppointmentsRoute: typeof ApiAppointmentsRouteWithChildren
  ApiInquiriesRoute: typeof ApiInquiriesRouteWithChildren
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ApiVehiclesRoute: typeof ApiVehiclesRouteWithChildren
  CuratorLoginRoute: typeof CuratorLoginRoute
  InventorySlugRoute: typeof InventorySlugRoute
  CuratorIndexRoute: typeof CuratorIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointments': {
      id: '/api/appointments'
      path: '/api/appointments'
      fullPath: '/api/appointments'
      preLoaderRoute: typeof ApiAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiries': {
      id: '/api/inquiries'
      path: '/api/inquiries'
      fullPath: '/api/inquiries'
      preLoaderRoute: typeof ApiInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicles': {
      id: '/api/vehicles'
      path: '/api/vehicles'
      fullPath: '/api/vehicles'
      preLoaderRoute: typeof ApiVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator/': {
      id: '/curator/'
      path: '/curator'
      fullPath: '/curator/'
      preLoaderRoute: typeof CuratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curator/login': {
      id: '/curator/login'
      path: '/curator/login'
      fullPath: '/curator/login'
      preLoaderRoute: typeof CuratorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$slug': {
      id: '/inventory/$slug'
      path: '/inventory/$slug'
      fullPath: '/inventory/$slug'
      preLoaderRoute: typeof InventorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointments/$id': {
      id: '/api/appointments/$id'
      path: '/$id'
      fullPath: '/api/appointments/$id'
      preLoaderRoute: typeof ApiAppointmentsIdRouteImport
      parentRoute: typeof ApiAppointmentsRoute
    }
    '/api/inquiries/$id': {
      id: '/api/inquiries/$id'
      path: '/$id'
      fullPath: '/api/inquiries/$id'
      preLoaderRoute: typeof ApiInquiriesIdRouteImport
      parentRoute: typeof ApiInquiriesRoute
    }
    '/api/uploads/$name': {
      id: '/api/uploads/$name'
      path: '/$name'
      fullPath: '/api/uploads/$name'
      preLoaderRoute: typeof ApiUploadsNameRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/api/vehicles/$id': {
      id: '/api/vehicles/$id'
      path: '/$id'
      fullPath: '/api/vehicles/$id'
      preLoaderRoute: typeof ApiVehiclesIdRouteImport
      parentRoute: typeof ApiVehiclesRoute
    }
  }
}

interface ApiAppointmentsRouteChildren {
  ApiAppointmentsIdRoute: typeof ApiAppointmentsIdRoute
}

const ApiAppointmentsRouteChildren: ApiAppointmentsRouteChildren = {
  ApiAppointmentsIdRoute: ApiAppointmentsIdRoute,
}

const ApiAppointmentsRouteWithChildren = ApiAppointmentsRoute._addFileChildren(
  ApiAppointmentsRouteChildren,
)

interface ApiInquiriesRouteChildren {
  ApiInquiriesIdRoute: typeof ApiInquiriesIdRoute
}

const ApiInquiriesRouteChildren: ApiInquiriesRouteChildren = {
  ApiInquiriesIdRoute: ApiInquiriesIdRoute,
}

const ApiInquiriesRouteWithChildren = ApiInquiriesRoute._addFileChildren(
  ApiInquiriesRouteChildren,
)

interface ApiUploadsRouteChildren {
  ApiUploadsNameRoute: typeof ApiUploadsNameRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsNameRoute: ApiUploadsNameRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

interface ApiVehiclesRouteChildren {
  ApiVehiclesIdRoute: typeof ApiVehiclesIdRoute
}

const ApiVehiclesRouteChildren: ApiVehiclesRouteChildren = {
  ApiVehiclesIdRoute: ApiVehiclesIdRoute,
}

const ApiVehiclesRouteWithChildren = ApiVehiclesRoute._addFileChildren(
  ApiVehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  ApiAppointmentsRoute: ApiAppointmentsRouteWithChildren,
  ApiInquiriesRoute: ApiInquiriesRouteWithChildren,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiMeRoute: ApiMeRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ApiVehiclesRoute: ApiVehiclesRouteWithChildren,
  CuratorLoginRoute: CuratorLoginRoute,
  InventorySlugRoute: InventorySlugRoute,
  CuratorIndexRoute: CuratorIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
